name: Deploy Angular Application to GitHub Pages

on:
  push:
    branches:
      - master  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@16

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: ng build --configuration production --base-href "/teia_c071615/" 

      - name: Configurar identidade do Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages@latest --dir=dist/teia_c071615 --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}