name: Deploy Angular Application to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: ng build --prod --base-href "/teia_c071615/"

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/teia_c071615
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
